// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:57781879-3667-45c9-8018-41b69e4cc1a5',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'client-hosting-mobilehub-969479029',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3926gfscq0njg.cloudfront.net',
    'aws_mobile_analytics_app_id': '357b6b8d543e4e63a0bdae612f34a32f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '9ca921c3-519c-43ca-9ea7-b19c890eaf4e',
    'aws_project_name': 'client-2018-01-28-17-28-26',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'client-mobilehub-969479029',
}

export default awsmobile;
