service: smartscale-app-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-2

  # 'iamRoleStatement' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
  # - path: url path is /notes
  # - method: POST request
  # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  #     domain api call
  # - authorizer: authenticate using the AWS IAM role
 

  count:
    handler: count.main
    events:
      - http:
          path: countData
          method: post
          cors: true
         
  
  get:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /count/{id}
    # - method: GET request
    handler: get.main
    events:
      - http:
          path: count/{id}
          method: get
          cors: true
  validate:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /count/{id}
    # - method: GET request
    handler: validateOrder.main
    events:
      - http:
          path: validate
          method: get
          cors: true
  
  createShipment:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /count/{id}
    # - method: POST request
    handler: shipment.create
    events:
      - http:
          path: shipment
          method: post
          cors: true

  createShipmentTransaction:
    # Defines an HTTP API endpoint that calls the main function in get.js
    # - path: url path is /count/{id}
    # - method: GET request
    handler: shipment.createTransaction
    events:
      - http:
          path: shipment/transaction
          method: post
          cors: true

  